name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: General checks, tests and coverage reporting
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js 20.11.0
      uses: actions/setup-node@v5
      with:
        node-version: 20.11.0

    - name: Install dependencies
      run: npm ci

    - name: Perform ESLint check
      run: npm run lint

    - name: Perform Licenses check
      run: npm run check-licenses

    - name: Perform dependency check
      run: npm run depcheck

    - name: Perform build
      run: npm run build-test

    - name: Run unit tests
      run: npm run coverage

    - name: Send report to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        # Pinned to v0.6.15 as workaround for 500 server errors
        # See: https://github.com/coverallsapp/coverage-reporter/issues/180
        coverage-reporter-version: v0.6.15
